DROP TABLE IF EXISTS CITY;  
CREATE TABLE CITY (  
	City_code INT AUTO_INCREMENT  PRIMARY KEY,  
	city_name VARCHAR(50) NOT NULL,  
	city_pincode INT(8) NOT NULL  
);  

INSERT INTO CITY VALUES (11, 'Delhi', 110001);
INSERT INTO CITY VALUES (12, 'Kanpur', 208001);
INSERT INTO CITY VALUES (13, 'Lucknow', 226001);
